#!/usr/bin/env python
# -*- coding: utf-8 -*-

import rospy
from sensor_msgs.msg import JointState
import sys


def talker():
    pub = rospy.Publisher('path_plan', JointState, queue_size=5)
    rospy.init_node("path_planner", anonymous=True)
    rate = rospy.Rate(10) # 10Hz
def path_computation():
def ask_user():
def inverse_kinematics():
    theta1=
    theta2=
    theta3=
    theta4=
    theta5=
    theta6=
    velocity1=
    velocity2=
    velocity3=
    velocity4=
    velocity5=
    velocity6=
if __name__ == '__main__':
    try:
        talker();
    except rospy.ROSInterruptException:
        pass
